name: Build and Deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          trunk build --release
          sed -i "s/\"\//\"\/yew-tictactoe\//g" dist/index.html
          sed -i "s/'\//'\/yew-tictactoe\//g" dist/index.html
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
